name: Deploy Serverless Application

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::701179923193:role/GitHubLambdaDeploymentPolicy
          aws-region: us-east-1

      - name: Package Lambda application
        run: |
          zip deployment.zip lambda_function.py contactus.html success.html

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name serverless-application \
            --zip-file fileb://deployment.zip

      - name: Verify Lambda deployment
        run: |
          aws lambda get-function \
            --function-name serverless-application
